image:
  file: .gitpod.Dockerfile

tasks:
  - name: Build & Run Tests
    init: mvn clean install
    command: mvn test

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - formulahendry.code-runner
    - redhat.java

ports:
  - port: 8080
    onOpen: open-preview

github:
  prebuilds:
    enabled: true
    addBadge: true
    addCheck: true
    runOnPullRequest: true
